# Service for hybrid system planning

Point x0 # initial state
Hybzono s # bounds on feasible states
Hybzono u # bounds on feasible inputs
Hybzono[] psi_arr # graph of function for system as function of time, time steps {0, ..., N-1}
Point[] xref_arr # reference state trajectory, time steps {1, ..., N}
std_msgs/Header[] t_arr # time stamps for plan, time steps {0, ..., N}
SparseMatrix q # state stage cost matrix
SparseMatrix r # input stage cost matrix
SparseMatrix qn # terminal state cost matrix
float64 tmax_sec # max time for planning
float64[] z_ws # warm start vector
---
bool success # whether planning was successful
PointTraj x_traj # state trajectory
PointTraj u_traj # input trajectory